name = "partykit-starter-party"
main = "party/index.ts"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "GameServer"
class_name = "GameServer"

[[migrations]]
tag = "v1"
new_classes = ["GameServer"]
